
return {
	["en"] =
	{
		["vote.added_on"] = "Added on:",
		["vote.expires_on"] = "Expires on:",
		["vote.author"] = "Author:",
		["vote.name"] = "Name:",
		["vote.write"] = "Write",
		["vote.write_helptext"] = "Describe your petition here.\nMarkdown is supported.",
		["vote.preview"] = "Preview",
		["vote.create"] = "Create",
		["vote.name_cant_be_empty"] = "Name must not be empty",
		["vote.description_cant_be_empty"] = "Description must not be empty",
		["vote.petitions"] = "Petitions",
		["vote.too_many_requested"] = "Too many petitions requested.",
		["vote.too_many_created"] = "You can only create %i petitions per day.",
		["vote.vote_on_self"] = "You cannot vote on your own petitions.",
		["vote.invalid_petition_requested"] = "Invalid petition (%i) requested.",
		["vote.invalid_vote"] = "The petition you are voting for (%i) does not exist.",
		["vote.expired_vote"] = "You can no longer vote on this petition.",
		["vote.not_fully_authed_p"] = "You are not fully authenticated, petition discarded.",
		["vote.not_fully_authed_v"] = "You are not fully authenticated, vote discarded.",
		["vote.name_too_long"] = "The name of your petition is longer then the maximum allowed length (%i/%i).",
		["vote.description_too_long"] = "The description of your petition is longer then the maximum allowed length (%i/%i).",
		["vote.ghostbanned"] = "You cannot use petitions while ghostbanned.",
		["vote.new_petitions"] = "%s has created a petition (%s).",

		["lag.freeze_penetrating"] = "Lag detected, freezing penetrating props.",
		["lag.cleanup"] = "Big lag detected! Clean up in %i seconds.",
		["lag.print_penetrating"] = "%s owns %i penetrating props!",
		["lag.too_many_props"] = "%s spawned a shitload of props in 1 tick, what the fuck is he doing?",
		["lag.timing_out"] = "Lost connection to server!",
		["lag.autobanned"] = "%s is a potential crasher and has been ghostbanned for %i seconds!",

		["cant_use_yet"] = "You have to play %i more hours on this server until you can use this feature.",
		["gcc_backdor_in_linux"] = "%s has used redhat gcc exploit on the server!",

		["advert.ghostbanned"] = "You are banned until: %s",
		["advert.pi_menu"] = "Press F2 to access the server menu.",
		["advert.petitions"] = "It would be nice if you signed some petitions in the F2 menu.",

		["pi_menu.title"] = "Player Menu",
		["pi_menu.no_render_on_lost_focus"] = "Disable render on lost focus?",
		["pi_menu.enable_auto_jump"] = "Enable auto jump?",
		["pi_menu.draw_spawnzone"] = "Draw spawn-zone limits?",
		["pi_menu.ulx_menu"] = "ULX Menu",
		["pi_menu.change_name"] = "Change Nickname",
		["pi_menu.change_nametag"] = "Change Nametag",
		["pi_menu.nametag_toggle"] = "Show nicks above head?",
		["pi_menu.nametags_localplayer"] = "Show your nick in 3rd person?",
		["pi_menu.enable_adverts"] = "Advertise this menu in chat?",
		["rules"] = "Rules",
		["set"] = "Set",
		["player_name"] = "Player Name",
		["player_nametag"] = "Player Name Tag",
		["new_name"] = "New name",
		["new_nametag"] = "New Name Tag",

		["no_noclip_in_pvp"] = "In PVP, can't use noclip for %i seconds.",

		["timer.shutdown"] = "The server will shut down in %.1f seconds!",
		["timer.cleanup"] = "The map will be cleaned up in %.1f seconds!",

		["scoreboard.ping"] = "%i ms",
		["scoreboard.playtime"] = "%i h.",
		["scoreboard.group"] = "Group: %s",
		["scoreboard.ent_count"] = "Num Entities: %i",
		["scoreboard.copy_steamid"] = "Copy SteamID",
		["scoreboard.open_profile"] = "Open Profile",
		["scoreboard.voice_volume"] = "Voice volume",
		["scoreboard.cache"] = "Cache: %i/%i",
		["scoreboard.player_count"] = "Players: %i/%i",
	},
	["ru"] =
	{
		["vote.added_on"] = "Добавлено:",
		["vote.expires_on"] = "Открыто до:",
		["vote.author"] = "Автор:",
		["vote.name"] = "Название:",
		["vote.write"] = "Писать",
		["vote.write_helptext"] = "Опишите здесь свою петицию.\nПоддерживется форматирование Markdown.",
		["vote.preview"] = "Предпросмотр",
		["vote.create"] = "Создать",
		["vote.name_cant_be_empty"] = "Название не может быть пустым",
		["vote.description_cant_be_empty"] = "Описание не может быть пустым",
		["vote.petitions"] = "Петиции",
		["vote.too_many_requested"] = "Запрошено слишком много петиций.",
		["vote.too_many_created"] = "Вы можете создовать не более %i петиций в сутки.",
		["vote.vote_on_self"] = "Вы не можете голосовать на свох петициях.",
		["vote.invalid_petition_requested"] = "Запрошенная петиция (%i) не существует.",
		["vote.invalid_vote"] = "Петиции за которую вы голосуете (%i) не существует.",
		["vote.expired_vote"] = "Вы больше не можете голосовать на этой петиции.",
		["vote.not_fully_authed_p"] = "Вы не полностью аутентифицированны, петиция отброшена.",
		["vote.not_fully_authed_v"] = "Вы не полностью аутентифицированны, голос отброшен.",
		["vote.name_too_long"] = "Имя вашей петиции больше максимально разрешённой длины (%i/%i).",
		["vote.description_too_long"] = "Описание вашей петиции больше максимально разрешённой длины (%i/%i).",
		["vote.ghostbanned"] = "Вы не можете использовать систему петиций в призрачном бане.",
		["vote.new_petitions"] = "%s создал петицию (%s).",

		["lag.freeze_penetrating"] = "Обнаружен лаг, фризим проникиющие пропы.",
		["lag.cleanup"] = "Обнаружен большой лаг! Очистка карты через %i секунд.",
		["lag.print_penetrating"] = "%s владеет %i проникиющими пропами!",
		["lag.too_many_props"] = "%s заспавнил дохуя пропов за 1 тик, чё за хуйню он творит?",
		["lag.timing_out"] = "Потерено соединение с сервером!",
		["lag.autobanned"] = "%s потенциальный крашер, и был забанен на %i секунд!",

		["cant_use_yet"] = "Вам нужно наиграть ещё %i часов на сервере прежде чем вы сможете использовать эту функцию.",
		["gcc_backdor_in_linux"] = "%s использовал redhat gcc эксплойт на сервере!",

		["advert.ghostbanned"] = "Вы забанены до: %s",
		["advert.pi_menu"] = "Нажмите F2 чтобы открыть меню сервера.",
		["advert.petitions"] = "Было бы неплохо если бы ты подписал несколько петиций в F2 меню.",

		["pi_menu.title"] = "Меню игрока",
		["pi_menu.no_render_on_lost_focus"] = "Не рисовать при потери фокуса?",
		["pi_menu.enable_auto_jump"] = "Включить авто-прыжок?",
		["pi_menu.advert"] = "Нажмите F2 чтобы открыть меню сервера.",
		["pi_menu.draw_spawnzone"] = "Отображать спавн-зону?",
		["pi_menu.ulx_menu"] = "ULX Меню",
		["pi_menu.change_name"] = "Изменить ник",
		["pi_menu.change_nametag"] = "Изменить тег",
		["pi_menu.nametag_toggle"] = "Показать ники над головой?",
		["pi_menu.nametags_localplayer"] = "Показать свой ник в 3-ем лице?",
		["pi_menu.enable_adverts"] = "Рекламировать это меню в чате?",
		["rules"] = "Правила",
		["set"] = "Поставить",
		["player_name"] = "Ник игрока",
		["player_nametag"] = "Тег игрока",
		["new_name"] = "Новый ник",
		["new_nametag"] = "Новый тег",

		["no_noclip_in_pvp"] = "В PVP, нельзя использовать noclip ещё %i секунд.",

		["timer.shutdown"] = "Сервер выключится через %.1f секунд!",
		["timer.cleanup"] = "Карта будет очищена через %.1f секунд!",

		["scoreboard.ping"] = "%i мс",
		["scoreboard.playtime"] = "%i ч.",
		["scoreboard.group"] = "Группа: %s",
		["scoreboard.ent_count"] = "Кол-во энтити: %i",
		["scoreboard.copy_steamid"] = "Копировать SteamID",
		["scoreboard.open_profile"] = "Открыть профель",
		["scoreboard.voice_volume"] = "Громкость",
		["scoreboard.cache"] = "Кеш: %i/%i",
		["scoreboard.player_count"] = "Игроки: %i/%i",
	}
}
